language: java

sudo: false

matrix:
  include:
    - jdk: openjdk11
      env: JAVA_BASE_IMAGE=openjdk:11
    - jdk: openjdk8
      env: JAVA_BASE_IMAGE=openjdk:8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - ./mvnw -B clean install -pl dubbo-maven-address-plugin
  - ./mvnw -pl dubbo-samples-transaction -Djava-image.name=${JAVA_BASE_IMAGE} -Ddocker.showLogs -Ddubbo.version=2.7.3-SNAPSHOT -Pdubbo-integration-test -B clean verify

#  - ./mvnw -B clean verify -Pdubbo-integration-test -Djava-image.name=${JAVA_BASE_IMAGE} -Ddubbo.version=2.7.3-SNAPSHOT



after_success:
  - bash <(curl -s https://codecov.io/bash)
