language: java

sudo: false

matrix:
  include:
    - jdk: openjdk11
      env: JAVA_BASE_IMAGE=openjdk:11
    - jdk: openjdk8
      env: JAVA_BASE_IMAGE=openjdk:8

cache:
  directories:
    - $HOME/.m2

install: true

jobs:
  include:
    - stage: test
      script: ./mvnw clean install
      name : "Compile and install project"
    - stage: integration test
      script: ./mvnw clean verify -Pdubbo-integration-test -Djava-image.name=${JAVA_BASE_IMAGE}
      name: "Run integration test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
